all:
	jsio_compile -j ../jsio-3.2 test.html -t websocket -t csp -e browser -o ../../static/test.html -g --vv

debug:
	jsio_compile -j ../jsio-3.2 test.html -t websocket -t csp -e browser -o ../../static/test.html -d --vv
